### ISSUE TITLE
タイトルロゴのデザインについて

### ISSUE THREAD

**Issue by Aso2101212** [ymnrio/2023Dev3Early#9]
今決まってる情報

おジャ魔女どれみ的なデザイン
サイトの背景がピンク
音楽記号をつける

で、あってるよね

**Comment by rei1104** [comment]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/117609540/233251974-3f823b4d-ae8d-44f7-846e-2cfcb8742abd.png)

**Comment by rei1104** [comment]
ざっくりやればこんな？
色合いとか

**Comment by Aso2101212** [comment]
おお！すごい！一番右に
<img width="1440" alt="スクリーンショット 2023-04-20 12 39 29" src="https://user-images.githubusercontent.com/117242986/233252255-f049045f-77e7-4a58-9aed-ab5916c0add9.png">
があったらいいかも！
五線譜に乗るかんじで

**Comment by rei1104** [comment]
了解！またなにかあったら言う！

**Comment by Aso2101212** [comment]
よしく！頑張って！

**Comment by rei1104** [comment]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/117609540/234357725-20812965-cd42-4ab5-a12e-0e947e3607ac.png)
